version: '3'

services:
    pass:
        build: .
        # restart: always
        # image: rss3/pass:latest
        container_name: pass
        ports:
            - '127.0.0.1:8080:8080'
        environment:
            NODE_ENV: production
